### ISSUE TITLE
function catxhALL() doesn't work as it supposed to?!

### ISSUE THREAD

**Issue by jamespatt** [andreasOrganization/hubot#26]
so far i tried this: 
```
module.exports = (robot) => {
    robot.catchALL((msg) => {
        let message = msg.message
        robot.send('hello')
        msg.finish()
    })
}
```
but it doesnt work.. any ideas?? 
@andreash92 can u take a look at this? thanks

**Comment by andreash92** [comment]
its catchAll not ALL @jamespatt

**Comment by jamespatt** [comment]
@andreash92 thanks for the fast reply!
you are right! its `catchAll()`
