### ISSUE TITLE
catchALL function does not exists?!

### ISSUE THREAD

**Issue by jamespatt** [andreasOrganization/hubot#28]
i tried this snippet here: 
```
module.exports = (robot) => {
    robot.catchALL((msg) => {
        let message = msg.message
        robot.send('hello')
        msg.finish()
    })
}
```
but i get an errorr that the function catchALL does not exists. any ideas? 
@andreash92 can u check it? i know u were working on this. thanks

**Comment by andreash92** [comment]
its catchAll not ALL @jamespatt
