### ISSUE TITLE
function catchALL() does not exists?!

### ISSUE THREAD

**Issue by jamespatt** [andreasOrganization/hubot#34]
i run this snippet:
```
	module.exports = (robot) => {
	    robot.catchALL((msg) => {
	        let message = msg.message
	        robot.send('hello')
	        msg.finish()
	    })
	}
```
but i get an error that the function catchALL does not exists. any ideas?? 
@andreash92 can u check this out? i know u were working on this.. thanks

**Comment by andreash92** [comment]
@jamespatt its catchAll not ALL (not caps lock)
